apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: nvidia/cuda:11.0-base
    command: [/bin/bash]
    args: ["-c", "ls /usr/bin/"]
  restartPolicy: OnFailure
