apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cv-workflow-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      Adapting hello world example.
      
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: cyr1ll/cv-pipeline-example
      command: [nvidia-smi]
      args: []
