random_seed: 80

#preprocess
data_path: "../datasets/understanding_cloud_organization"
image_out_dir: "./images_out"
masks_out_dir: "./masks_out"
resize_height: 320
resize_width: 640
device: gpu
batch_size: 32

#train
image_in_dir: "./images_out"
masks_in_dir: "./masks_out"
checkpoint_dir: "./checkpoints"
epochs: 1
optimizer: Adam
arch: Unet
encoder: resnet50
lr_encoder: 1e-3
lr_decoder: 1e-2
num_workers: 16


#postprocess
threshold: 0.4
min_mask_size: 10000
